controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
ensavoirplus:
    path: /ensavoirplus
    controller: App\Controller\AccueilController::ensavoirplus


