<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM3WEu20\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM3WEu20/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM3WEu20.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM3WEu20\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM3WEu20\App_KernelDevDebugContainer([
    'container.build_hash' => 'M3WEu20',
    'container.build_id' => '7c72ab5f',
    'container.build_time' => 1706608033,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM3WEu20');
